name: Build FlClash

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          dart setup.dart android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FlClash-APK
          path: build/app/outputs/flutter-apk/*.apk
